########## Testcase 0: Failed ##########
Expected Output: 
Yes
Your Output: 
give
Exception in thread "main" java.lang.ArithmeticException: / by zero
	at SeparateChainingHashST.hash(Solution.java:10)
	at SeparateChainingHashST.put(Solution.java:17)
	at Solution.main(Solution.java:62)
----------------------------------------
########## Testcase 1: Failed ##########
Expected Output: 
No
Your Output: 
two
Exception in thread "main" java.lang.ArithmeticException: / by zero
	at SeparateChainingHashST.hash(Solution.java:10)
	at SeparateChainingHashST.put(Solution.java:17)
	at Solution.main(Solution.java:62)
----------------------------------------
########## Testcase 2: Failed ##########
Expected Output: 
No
Your Output: 
ive
Exception in thread "main" java.lang.ArithmeticException: / by zero
	at SeparateChainingHashST.hash(Solution.java:10)
	at SeparateChainingHashST.put(Solution.java:17)
	at Solution.main(Solution.java:62)
----------------------------------------
########## Testcase 3: Failed ##########
Expected Output: 
No
Your Output: 
wi
Exception in thread "main" java.lang.ArithmeticException: / by zero
	at SeparateChainingHashST.hash(Solution.java:10)
	at SeparateChainingHashST.put(Solution.java:17)
	at Solution.main(Solution.java:62)
----------------------------------------
########## Testcase 4: Failed ##########
Expected Output: 
Yes
Your Output: 
h
Exception in thread "main" java.lang.ArithmeticException: / by zero
	at SeparateChainingHashST.hash(Solution.java:10)
	at SeparateChainingHashST.put(Solution.java:17)
	at Solution.main(Solution.java:62)
----------------------------------------
########## Testcase 5: Failed ##########
Expected Output: 
Yes
Your Output: 
aabkl
Exception in thread "main" java.lang.ArithmeticException: / by zero
	at SeparateChainingHashST.hash(Solution.java:10)
	at SeparateChainingHashST.put(Solution.java:17)
	at Solution.main(Solution.java:62)
----------------------------------------
