########## Testcase 0: Failed ##########
Expected Output: 
Yes
Your Output: 
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at Solution.main(Solution.java:42)
----------------------------------------
########## Testcase 1: Failed ##########
Expected Output: 
No
Your Output: 
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at Solution.main(Solution.java:42)
----------------------------------------
########## Testcase 2: Failed ##########
Expected Output: 
No
Your Output: 
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at Solution.main(Solution.java:42)
----------------------------------------
########## Testcase 3: Failed ##########
Expected Output: 
No
Your Output: 
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at Solution.main(Solution.java:42)
----------------------------------------
########## Testcase 4: Failed ##########
Expected Output: 
Yes
Your Output: 
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at Solution.main(Solution.java:45)
----------------------------------------
########## Testcase 5: Failed ##########
Expected Output: 
Yes
Your Output: 
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at Solution.main(Solution.java:42)
----------------------------------------
